### ISSUE TITLE
优酷出现黑屏

### ISSUE THREAD

**Issue by oneone1995** [jc3213/soWatch-mk2#1]
拦截xml请求和替换播放器均试过。

**Comment by greying** [comment]
@oneone1995 清除缓存

**Comment by jc3213** [comment]
请勿讨论广告过滤相关问题，目前维护这个项目仅是我的兴趣。如果可以的话请自行fork并进行修改。目前项目基于LGPL 3.0，对代码的要求并不是那么严格。
